services:
  db:
    container_name: pg_db
    image: 'postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=consulta
    volumes:
      - postgres-data:/var/lib/postgresql/data
  client:
    container_name: consulta-processual-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    depends_on:
      - db

volumes:
  postgres-data:
